# Generated by Django 3.2.4 on 2021-10-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('pro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=256)),
                ('pro_provider', models.CharField(max_length=256)),
                ('pro_existences', models.CharField(max_length=25)),
                ('pro_description', models.CharField(max_length=256)),
            ],
        ),
    ]
