# Generated by Django 3.2.4 on 2021-10-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pro_category',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
