# Generated by Django 3.2.4 on 2021-10-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_pro_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pro_date',
            field=models.DateTimeField(null=True),
        ),
    ]
