# Generated by Django 3.2.8 on 2021-10-13 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('pro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=256)),
                ('pro_provider', models.CharField(max_length=256)),
                ('pro_existences', models.CharField(max_length=256)),
                ('pro_date', models.DateTimeField(null=True)),
                ('pro_description', models.CharField(max_length=456)),
                ('pro_category', models.CharField(max_length=256)),
            ],
        ),
    ]
